-- Bảng theo dõi thông báo đã đọc của học sinh
CREATE TABLE [dbo].[DocThongBao](
	[maDocTB] [int] IDENTITY(1,1) NOT NULL,
	[maHS] [int] NOT NULL,
	[maTB] [int] NOT NULL,
	[ngayDoc] [datetime] NULL DEFAULT GETDATE(),
PRIMARY KEY CLUSTERED 
(
	[maDocTB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[maHS] ASC,
	[maTB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DocThongBao]  WITH CHECK ADD FOREIGN KEY([maHS])
REFERENCES [dbo].[HocSinh] ([maHS])
GO

ALTER TABLE [dbo].[DocThongBao]  WITH CHECK ADD FOREIGN KEY([maTB])
REFERENCES [dbo].[ThongBao] ([maTB])
GO
